









<BoxL>:
    b1: b1
    orientation: "vertical"
    BoxLayout:



        size_hint_y: .1
        pos_hint: {"center_y":0.95}
        height: 200
        Label:
            pos_hint: {"x":0}
            size_hint: 0.15,1
            #size_hint_y: .1
            text: "Status:"
            font_size: 25


        Button:
            id: b1
            background_color: 1,1,1,1
            #size_hint: 0.1,1
            size: 30,30
            width: 100
            height: "10dp"
            pos_hint: {"center_x":.5}
            on_press: root.checkConnection()

    BoxLayout:
        Label:
            text: "saf"


